checks:
    php:
        code_rating: true
        duplication: true
        excluded_dependencies:
            - kdn/yii2-domain-validator
tools:
    php_code_coverage:
        enabled: true
    external_code_coverage:
        timeout: 600
